export const EMOTIONSDATA = {
    'Janeiro': [
      {
        id: "1",
        label: "Triste",
        value: 15,
        color: "#c1d1df",
      },
      {
        id: "2",
        label: "Neutro",
        value: 5,
        color: "#a3d3fd",
      },
      {
        id: "3",
        label: "Bem",
        value: 5,
        color: "#FCDEC0",
      },
      {
        id: "4",
        label: "Feliz",
        value: 6,
        color: "#ffe599",
      },
    ],
    'Fevereiro': [
      {
        id: "1",
        label: "Triste",
        value: 5,
        color: "#c1d1df",
      },
      {
        id: "2",
        label: "Neutro",
        value: 10,
        color: "#a3d3fd",
      },
      {
        id: "3",
        label: "Bem",
        value: 11,
        color: "#FCDEC0",
      },
      {
        id: "4",
        label: "Feliz",
        value: 7,
        color: "#ffe599",
      },
    ],
    'Março': [
      {
        id: "1",
        label: "Triste",
        value: 7,
        color: "#c1d1df",
      },
      {
        id: "2",
        label: "Neutro",
        value: 6,
        color: "#a3d3fd",
      },
      {
        id: "3",
        label: "Bem",
        value: 7,
        color: "#FCDEC0",
      },
      {
        id: "4",
        label: "Feliz",
        value: 9,
        color: "#ffe599",
      }
    ]

  };

export const DAILYEMOTIONS = {
  'Janeiro': [
    { x: 1, y: "Triste" },
    { x: 2, y: "Triste" },
    { x: 3, y: "Triste" },
    { x: 4, y: "Triste" },
    { x: 5, y: "Triste" },
    { x: 6, y: "Triste" },
    { x: 7, y: "Neutro" },
    { x: 8, y: "Bem" },
    { x: 10, y: "Neutro" },
    { x: 11, y: "Neutro" },
    { x: 12, y: "Neutro" },
    { x: 13, y: "Triste" },
    { x: 14, y: "Triste" },
    { x: 15, y: "Bem" },
    { x: 16, y: "Bem" },
    { x: 17, y: "Bem" },
    { x: 18, y: "Neutro" },
    { x: 19, y: "Feliz" },
    { x: 20, y: "Bem" },
    { x: 21, y: "Triste" },
    { x: 22, y: "Triste" },
    { x: 23, y: "Triste" },
    { x: 24, y: "Feliz" },
    { x: 25, y: "Feliz" },
    { x: 26, y: "Triste" },
    { x: 27, y: "Triste" },
    { x: 28, y: "Feliz" },
    { x: 29, y: "Triste" },
    { x: 30, y: "Triste" },
    { x: 31, y: "Feliz" },
  ],
  'Fevereiro': [
    { x: 1, y: "Triste" },
    { x: 2, y: "Triste" },
    { x: 3, y: "Triste" },
    { x: 4, y: "Triste" },
    { x: 5, y: "Triste" },
    { x: 6, y: "Feliz" },
    { x: 7, y: "Neutro" },
    { x: 8, y: "Neutro" },
    { x: 10, y: "Neutro" },
    { x: 11, y: "Feliz" },
    { x: 12, y: "Feliz" },
    { x: 13, y: "Triste" },
    { x: 14, y: "Triste" },
    { x: 15, y: "Triste" },
    { x: 16, y: "Triste" },
    { x: 17, y: "Neutro" },
    { x: 18, y: "Neutro" },
    { x: 19, y: "Triste" },
    { x: 20, y: "Neutro" },
    { x: 21, y: "Triste" },
    { x: 22, y: "Neutro" },
    { x: 23, y: "Triste" },
    { x: 24, y: "Neutro" },
    { x: 25, y: "Feliz" },
    { x: 26, y: "Neutro" },
    { x: 27, y: "Feliz" },
    { x: 28, y: "Neutro" },
    { x: 29, y: "Triste" },
    { x: 30, y: "Triste" },
  ],
  'Março': [
    { x: 1, y: "Triste" },
    { x: 2, y: "Triste" },
    { x: 3, y: "Triste" },
    { x: 4, y: "Triste" },
    { x: 5, y: "Triste" },
    { x: 6, y: "Triste" },
    { x: 7, y: "Triste" },
    { x: 8, y: "Neutro" },
    { x: 10, y: "Neutro" },
    { x: 11, y: "Neutro" },
    { x: 12, y: "Neutro" },
    { x: 13, y: "Neutro" },
    { x: 14, y: "Neutro" },
    { x: 15, y: "Bem" },
    { x: 16, y: "Bem" },
    { x: 17, y: "Bem" },
    { x: 18, y: "Bem" },
    { x: 19, y: "Bem" },
    { x: 20, y: "Bem" },
    { x: 21, y: "Bem" },
    { x: 22, y: "Feliz" },
    { x: 23, y: "Feliz" },
    { x: 24, y: "Feliz" },
    { x: 25, y: "Feliz" },
    { x: 26, y: "Feliz" },
    { x: 27, y: "Feliz" },
    { x: 28, y: "Feliz" },
    { x: 29, y: "Feliz" },
    { x: 30, y: "Feliz" },
  ],
}